require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HostelRoomsController do

  # This should return the minimal set of attributes required to create a valid
  # HostelRoom. As you add validations to HostelRoom, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all hostel_rooms as @hostel_rooms" do
      hostel_room = HostelRoom.create! valid_attributes
      get :index
      assigns(:hostel_rooms).should eq([hostel_room])
    end
  end

  describe "GET show" do
    it "assigns the requested hostel_room as @hostel_room" do
      hostel_room = HostelRoom.create! valid_attributes
      get :show, :id => hostel_room.id.to_s
      assigns(:hostel_room).should eq(hostel_room)
    end
  end

  describe "GET new" do
    it "assigns a new hostel_room as @hostel_room" do
      get :new
      assigns(:hostel_room).should be_a_new(HostelRoom)
    end
  end

  describe "GET edit" do
    it "assigns the requested hostel_room as @hostel_room" do
      hostel_room = HostelRoom.create! valid_attributes
      get :edit, :id => hostel_room.id.to_s
      assigns(:hostel_room).should eq(hostel_room)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HostelRoom" do
        expect {
          post :create, :hostel_room => valid_attributes
        }.to change(HostelRoom, :count).by(1)
      end

      it "assigns a newly created hostel_room as @hostel_room" do
        post :create, :hostel_room => valid_attributes
        assigns(:hostel_room).should be_a(HostelRoom)
        assigns(:hostel_room).should be_persisted
      end

      it "redirects to the created hostel_room" do
        post :create, :hostel_room => valid_attributes
        response.should redirect_to(HostelRoom.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hostel_room as @hostel_room" do
        # Trigger the behavior that occurs when invalid params are submitted
        HostelRoom.any_instance.stub(:save).and_return(false)
        post :create, :hostel_room => {}
        assigns(:hostel_room).should be_a_new(HostelRoom)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HostelRoom.any_instance.stub(:save).and_return(false)
        post :create, :hostel_room => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hostel_room" do
        hostel_room = HostelRoom.create! valid_attributes
        # Assuming there are no other hostel_rooms in the database, this
        # specifies that the HostelRoom created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HostelRoom.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => hostel_room.id, :hostel_room => {'these' => 'params'}
      end

      it "assigns the requested hostel_room as @hostel_room" do
        hostel_room = HostelRoom.create! valid_attributes
        put :update, :id => hostel_room.id, :hostel_room => valid_attributes
        assigns(:hostel_room).should eq(hostel_room)
      end

      it "redirects to the hostel_room" do
        hostel_room = HostelRoom.create! valid_attributes
        put :update, :id => hostel_room.id, :hostel_room => valid_attributes
        response.should redirect_to(hostel_room)
      end
    end

    describe "with invalid params" do
      it "assigns the hostel_room as @hostel_room" do
        hostel_room = HostelRoom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HostelRoom.any_instance.stub(:save).and_return(false)
        put :update, :id => hostel_room.id.to_s, :hostel_room => {}
        assigns(:hostel_room).should eq(hostel_room)
      end

      it "re-renders the 'edit' template" do
        hostel_room = HostelRoom.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HostelRoom.any_instance.stub(:save).and_return(false)
        put :update, :id => hostel_room.id.to_s, :hostel_room => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hostel_room" do
      hostel_room = HostelRoom.create! valid_attributes
      expect {
        delete :destroy, :id => hostel_room.id.to_s
      }.to change(HostelRoom, :count).by(-1)
    end

    it "redirects to the hostel_rooms list" do
      hostel_room = HostelRoom.create! valid_attributes
      delete :destroy, :id => hostel_room.id.to_s
      response.should redirect_to(hostel_rooms_url)
    end
  end

end
