require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SearchesController do

  # This should return the minimal set of attributes required to create a valid
  # Search. As you add validations to Search, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all searches as @searches" do
      search = Search.create! valid_attributes
      get :index
      assigns(:searches).should eq([search])
    end
  end

  describe "GET show" do
    it "assigns the requested search as @search" do
      search = Search.create! valid_attributes
      get :show, :id => search.id.to_s
      assigns(:search).should eq(search)
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested search" do
      search = Search.create! valid_attributes
      expect {
        delete :destroy, :id => search.id.to_s
      }.to change(Search, :count).by(-1)
    end

    it "redirects to the searches list" do
      search = Search.create! valid_attributes
      delete :destroy, :id => search.id.to_s
      response.should redirect_to(searches_url)
    end
  end

end

